### ISSUE TITLE
Front panel

### ISSUE THREAD

**Issue by Fisheye3D** [leadustin/QIDI-up2date-english#1]
Can you provide how to get to the screen to replace it, I can only get to the bottom 2 screws. Does the front panel come off?

**Comment by leadustin** [comment]
Just as you unscrew the two lower screws with an Allen key, unscrew the two upper screws. The front panel does not need to be removed for this. Just feel where the screws are.

**Comment by Fisheye3D** [comment]
> Just as you unscrew the two lower screws with an Allen key, unscrew the two upper screws. The front panel does not need to be removed for this. Just feel where the screws are.

Yours must be different as that is impossible to do on mine. 
![image](https://github.com/leadustin/QIDI-up2date-english/assets/78997080/a19e7539-81f2-40d9-9fcb-2bbe714548a2)

**Comment by leadustin** [comment]
I honestly thought that there was no difference in the display between Max3 and Plus3. I can't help you there. But I would check if there are other screws holding the front panel. Because on your display the screws are mounted from the other side than on my display. See if you can remove the side panels.
